### ISSUE TITLE
Logger no se instancia correctamente.

### ISSUE THREAD

**Issue by mlafroce** [marianorodriguez/75.52-MensajerO#24]
- El logger no se instancia si no encuentra el archivo config/config.json
- Para guardar su status realiza un open y close (utilizar [esta alternativa](http://www.cplusplus.com/reference/ostream/ostream/flush/))
- Se podría poner el archivo en el stack en vez del heap
- No es thread-safe

**Comment by marianorodriguez** [comment]
1-> crear una excepcion fileNotFound
2-> cambiemos a flush!
3-> no entiendo a qué te referis
4-> idem 3. (ejemplo?)

**Comment by mlafroce** [comment]
El 3 se arreglaría cambiando el puntero ofstream\* por un atributo ofstream a secas. Si bien funcionalmente no cambia nada, es más RAII
El 4 se arregla con mutex. Si 2 hilos están usando el logger en simultaneo (algo muy probable siendo un singleton), puede terminar entremezclando las salidas. Además, si 2 hilos llaman al logger en simultaneo cuando recién se inicializa (algo muy poco probable), puede que ambos llamen al "logInstance = new logger();", ahí también debería ir un mutex.
Igual no se que tanto uso de hilos va a hacer el mongoose para atender los requests, así que podés postergarlo, pero es importante asentar ese limitante en algún lado.

**Comment by marianorodriguez** [comment]
arreglé estos puntos en el branch loggerFix pero estoy sufriendo un problema: si ven el codigo de loggerTests van a notar que siempre invoco Loggers nuevos, y nunca borro los viejos, quedando mucha RAM colgada. si hago delete al final de cada test, se queda clavado por razones desconocidas. Agradecería una mano ya que no tengo idea por qué pasa esto :) 
@mlafroce @fernandocortes10 @franery
