### ISSUE TITLE
server - arreglar CMake

### ISSUE THREAD

**Issue by marianorodriguez** [marianorodriguez/75.52-MensajerO#25]
la idea es que se puedan compilar y correr el main y las pruebas desde el makefile generado por CMake, y que se generen todas las carpetas necesarias (como la del config.json)

**Comment by mlafroce** [comment]
Ya están armados los modulos main y test, y algunos submodulos como services (para servicios rest) y services rest. Falta que coordinemos como agregar las bibliotecas externas (mongoose y rocksdb), que está medio turbio como compila.
Falta estandarizar otros submodulos (database por ejemplo)
