### ISSUE TITLE
server - pruebas de DataBase

### ISSUE THREAD

**Issue by marianorodriguez** [marianorodriguez/75.52-MensajerO#27]
-> keys "user1/user2" == "user2/user1" ?
-> cerrar y abrir la DB para chequear la persistencia?
-> probar keys con caracteres invalidos? (cualquier cosa que no sea una letra o numero) se podria lanzar una exception para el caso que sea invalida una key
-> "user1" == "USER1" == "UsEr1" ?? (convertir todos los usernames a lowercase)

**Comment by franery** [comment]
1) No es lo mismo. Diria que pongamos el user q este 1ro alfabeticamente (por ASCII) primero. 
2) Ahi agrego una prueba
3) Si, le podes poner caracteres invalidos a la key. Incluso podes poner NULL caracteres, le podes mandar cualquier cosa y anda. 
4) Son todas distintas keys.

**Comment by marianorodriguez** [comment]
1) quise decir que esas 2 claves deberian devolver el mismo value. es tarea de la DB reordenar los usernames en orden alfabetico.
2) (Y)
3) es raro que puedas poner null caracteres, habría que tratar de impedir eso
4) está bien que la DB las interprete como distintas, pero no habria que evitarlo?

**Comment by marianorodriguez** [comment]
3) aunque talvez lo de validar un username sea responsabilidad del cliente...

**Comment by franery** [comment]
1) Ah te entendi mal
3) Lo q va a estar en las keys son usernames, y los usernames ya tendrian q estar validados antes
4) Votacion de grupo :P

**Comment by marianorodriguez** [comment]
3) estoy de acuerdo
4) estoy de acuerdo

@mlafroce @fernandocortes10 como hacemos con 4) ?

**Comment by fernandocortes1990** [comment]
es lo que hablamos por facebook?
para los usernames yo creo que si, todo en lower case.
el cliente pide el username y lo envia a validar al server. el server le dice si es valido o no.
