### ISSUE TITLE
server - estructura DataBase

### ISSUE THREAD

**Issue by marianorodriguez** [marianorodriguez/75.52-MensajerO#33]
hacer abstracta la clase DataBase. De esta heredan ChatDB y UserDB. Luego cada una de estas implementa write y read con la misma firma! (key, value)

http://es.wikipedia.org/wiki/Principio_de_sustituci%C3%B3n_de_Liskov

![captura de pantalla de 2015-04-04 18 19 06](https://cloud.githubusercontent.com/assets/11478307/6994631/2f78ac02-daf7-11e4-9ae5-b40646c6bad1.png)

**Comment by franery** [comment]
Lo arreglo como hablamos por fb
