### ISSUE TITLE
client, server - definir cuales van a ser los datos a transmitir entre ambos y en que formato.

### ISSUE THREAD

**Issue by fernandocortes1990** [marianorodriguez/75.52-MensajerO#36]

**Comment by marianorodriguez** [comment]
te referis al json que se mande desde el cliente al servidor? siempre y cuando tengas los mismos datos, podes hacerlo como mejor te parezca y despues le enchufamos una especie de Adapter en el medio. Sino, vas a tener que seguir la estructura de las clases serializadas en C++. Podés crear cualquiera y tirar cout de sus datos serializados para ver la estructura y copiarla del lado del cliente.

**Comment by fernandocortes1990** [comment]
Ahora subo los servicios qe ideamos

**Comment by fernandocortes1990** [comment]
archivo services.odt en carpeta doc
