### ISSUE TITLE
server - problema con prueba de Logger

### ISSUE THREAD

**Issue by marianorodriguez** [marianorodriguez/75.52-MensajerO#37]
recién ejecuté las pruebas y LoggerTests::should_be_thread_safe tiró error. Volví a ejecutar varias veces mas y estaba todo ok, asi que esa prueba está teniendo algún defecto por algún lado que hace que falle de vez en cuando, por favor mirar.

**Comment by mlafroce** [comment]
Lo vi, aumentando la cantidad de hilos pasa más seguido, me lo tomo como pendiente.

**Comment by mlafroce** [comment]
Se agregaron los mutex correspondientes, y también al GetInstance (ahora utiliza double check)
