### ISSUE TITLE
client - implementar utilities

### ISSUE THREAD

**Issue by marianorodriguez** [marianorodriguez/75.52-MensajerO#38]
-> Logger
-> MD5 para encriptar las contraseñas que se le manden al servidor.
-> base64 para codificar/decodificar las fotos de perfil de los usuarios.

**Comment by marianorodriguez** [comment]
-> Implementar un moódulo java "Locater" que dado 2 ints, latitud y longitud, devuelva un string con el nombre del barrio / zona

**Comment by fernandocortes1990** [comment]
base64 y md5 estan

**Comment by fernandocortes1990** [comment]
falta implementar el logger

**Comment by marianorodriguez** [comment]
el logger ya fue implementado para java
