### ISSUE TITLE
server - más pruebas para DB

### ISSUE THREAD

**Issue by marianorodriguez** [marianorodriguez/75.52-MensajerO#40]
subí algunas pruebas nuevas, y hay un par que estan fallando, mirar por favor.

**Comment by franery** [comment]
Lo de que tenga caracteres invalidos deberia ser checkeado en la aplicacion. No tiene q conectarse con el server para depues decirle q no ingrese espacios o caracteres raros. La de vector vacio te la acepto aunq no deberia pasar jaja, ahi arreglo esa

**Comment by marianorodriguez** [comment]
jajaja ok, lo de user valido se chequea en el cliente
