### ISSUE TITLE
cliente, servidor - integrar con el server y ver la frecuencia necesaria del llamado a los servicios para que no queme el server ni se vea laggueada la app

### ISSUE THREAD

**Issue by fernandocortes1990** [marianorodriguez/75.52-MensajerO#59]

**Comment by fernandocortes1990** [comment]
con dos usuarios (emuladores) anduvo bien la frecuencia seteada.

**Comment by mlafroce** [comment]
Estuve haciendo pruebas agregando hilos al servidor, el cuello de botella está en la DB, hay que revisar si se puede evitar abrir y cerrarla constantemente.
