### ISSUE TITLE
server, client - borrado de chats

### ISSUE THREAD

**Issue by fernandocortes1990** [marianorodriguez/75.52-MensajerO#74]
creo que deberiamos hacer un nuevo service que mande al server cuando el user borra un chat. para que el server tambien lo borre o lo marque como "no deseado" para que no se lo envie al cliente en la proxima conexion.

**Comment by marianorodriguez** [comment]
el servicio ya está andando del lado del servidor

**Comment by fernandocortes1990** [comment]
fijate de darle una vuelta mas marian porque le tire por el postman y no m devolvio nada.

**Comment by marianorodriguez** [comment]
el código es correcto, lo unico q se me ocurre es q esté lanzando alguna excepcion q se atrapa mas arriba. Lo voy a mirar mejor

**Comment by fernandocortes1990** [comment]
fixed on commit 33ffceb7cb2dc67d56a9dbc2fd8e7562b45b7692
