### ISSUE TITLE
probar server-cliente con Docker/maquina limpia

### ISSUE THREAD

**Issue by marianorodriguez** [marianorodriguez/75.52-MensajerO#87]
tenemos que estar seguros de que todo funciona bien, siguiendo los pasos del readme con una maquina bien limpia, o un repo en Docker

**Comment by franery** [comment]
Probado en maquina virtual. Solo tuve q instalar g++ y cmake, anda bien

**Comment by marianorodriguez** [comment]
agregamos esos sudos a las precondiciones del instalador?

**Comment by marianorodriguez** [comment]
parece que ya fueron agregados al instalador de dependencias, se puede cerrar este ticket.
